btrealestate/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.homeView, name='home'),
    path('', include('pages.urls')),
    path('listings/', include('listings.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/urls.py
from django.urls import path
from .import views

app_name = 'listings'

urlpatterns = [
    path('', views.listingsView, name='listingsView'),
    path('<int:listing_id>', views.listingView, name='listingView'),
    path('search', views.searchView, name='searchView'),
]

pages/urls.py
from django.urls import path, include
from .import views

app_name = 'pages'

urlpatterns = [
    path('about', views.aboutView, name='about'),
]

listings/models.py
from django.db import models
from datetime import datetime
from realtors.models import Realtor

class Listing(models.Model):
    realtor = models.ForeignKey(Realtor, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=20)
    description = models.TextField(blank=True)
    price = models.IntegerField()
    bedrooms = models.IntegerField()
    bathrooms = models.DecimalField(max_digits=2, decimal_places=1)
    garage = models.IntegerField(default=0)
    sqft = models.IntegerField()
    lot_size = models.DecimalField(max_digits=5, decimal_places=1)
    photo_main = models.ImageField(upload_to='photos/')
    photo_1 = models.ImageField(upload_to='photos/', blank=True)
    photo_2 = models.ImageField(upload_to='photos/', blank=True)
    photo_3 = models.ImageField(upload_to='photos/', blank=True)
    photo_4 = models.ImageField(upload_to='photos/', blank=True)
    photo_5 = models.ImageField(upload_to='photos/', blank=True)
    photo_6 = models.ImageField(upload_to='photos/', blank=True)
    is_published = models.BooleanField(default=True)
    list_date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.title

pages/models.py
from django.db import models

# Create your models here.

realtors/models.py
from django.db import models
from datetime import datetime

class Realtor(models.Model):
    name = models.CharField(max_length=200)
    photo = models.ImageField(upload_to='realtors/')
    description = models.TextField(blank=True)
    phone = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    is_mvp = models.BooleanField(default=False)
    hire_date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.name

btrealestate/views.py
from django.shortcuts import render
from django.http import HttpResponse

def homeView(request):
    template = 'index.html'

    return render(request, template)

listings/views.py
from django.shortcuts import render

def listingsView(request):
    template = 'listings/listings.html'

    return render(request, template)

def listingView(request):
    template = 'listings/listing.html'

    return render(request, template)

def searchView(request):
    template = 'listings/search.html'

    return render(request, template)

pages/views.py
from django.shortcuts import render

def aboutView(request):
    template = 'pages/about.html'

    return render(request, template)

realtors/views.py
from django.shortcuts import render

# Create your views here.

btrealestate/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static "css/all.css" %}">
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
  <!-- Custom -->
  <link rel="stylesheet" href="{% static "css/style.css" %}">
  <!-- lightbox -->
  <link rel="stylesheet" href="{% static "css/lightbox.min.css" %}">

  <title>
    {% block title %}

    {% endblock %}
  </title>
</head>

<body>
  <!-- Top Bar -->
  {% include "topbar.html" %}

  <!-- Navbar -->
  {% include "navbar.html" %}

  {% block content %}

  {% endblock %}

  <!-- Footer -->
  {% include "footer.html" %}

  <script src="{% static "js/jquery-3.3.1.min.js" %}"></script>
  <script src="{% static "assets/js/bootstrap.bundle.min.js" %}"></script>
  <script src="{% static "assets/js/main.js" %}"></script>
  <script src="{% static "assets/js/lightbox.min.js" %}"></script>
</body>
</html>

btrealestate/templates/footer.html
{% load static %}

<!-- Footer -->
<footer id="main-footer" class="py-4 bg-primary text-white text-center">
  Copyright &copy;
  <span class="year"></span> BT Real Estate
</footer>

btrealestate/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}

{% endblock %}

{% block content %}
<!-- Showcase -->
<section id="showcase" style="background: url(/static/images/showcase.jpg);">
  <div class="container text-center">
    <div class="home-search p-5">
      <div class="overlay p-5">
        <h1 class="display-4 mb-4">
          Property Searching Just Got So Easy
        </h1>
        <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae quas, asperiores eveniet vel nostrum magnam
          voluptatum tempore! Consectetur, id commodi!</p>
        <div class="search">
          <form action="search.html">
            <!-- Form Row 1 -->
            <div class="form-row">
              <div class="col-md-4 mb-3">
                <label class="sr-only">Keywords</label>
                <input type="text" name="keywords" class="form-control" placeholder="Keyword (Pool, Garage, etc)">
              </div>

              <div class="col-md-4 mb-3">
                <label class="sr-only">City</label>
                <input type="text" name="city" class="form-control" placeholder="City">
              </div>

              <div class="col-md-4 mb-3">
                <label class="sr-only">State</label>
                <select name="state" class="form-control">
                  <option selected="true" disabled="disabled">State (All)</option>
                  <option value="AL">Alabama</option>
                  <option value="AK">Alaska</option>
                  <option value="AZ">Arizona</option>
                  <option value="AR">Arkansas</option>
                  <option value="CA">California</option>
                  <option value="CO">Colorado</option>
                  <option value="CT">Connecticut</option>
                  <option value="DE">Delaware</option>
                  <option value="DC">District Of Columbia</option>
                  <option value="FL">Florida</option>
                  <option value="GA">Georgia</option>
                  <option value="HI">Hawaii</option>
                  <option value="ID">Idaho</option>
                  <option value="IL">Illinois</option>
                  <option value="IN">Indiana</option>
                  <option value="IA">Iowa</option>
                  <option value="KS">Kansas</option>
                  <option value="KY">Kentucky</option>
                  <option value="LA">Louisiana</option>
                  <option value="ME">Maine</option>
                  <option value="MD">Maryland</option>
                  <option value="MA">Massachusetts</option>
                  <option value="MI">Michigan</option>
                  <option value="MN">Minnesota</option>
                  <option value="MS">Mississippi</option>
                  <option value="MO">Missouri</option>
                  <option value="MT">Montana</option>
                  <option value="NE">Nebraska</option>
                  <option value="NV">Nevada</option>
                  <option value="NH">New Hampshire</option>
                  <option value="NJ">New Jersey</option>
                  <option value="NM">New Mexico</option>
                  <option value="NY">New York</option>
                  <option value="NC">North Carolina</option>
                  <option value="ND">North Dakota</option>
                  <option value="OH">Ohio</option>
                  <option value="OK">Oklahoma</option>
                  <option value="OR">Oregon</option>
                  <option value="PA">Pennsylvania</option>
                  <option value="RI">Rhode Island</option>
                  <option value="SC">South Carolina</option>
                  <option value="SD">South Dakota</option>
                  <option value="TN">Tennessee</option>
                  <option value="TX">Texas</option>
                  <option value="UT">Utah</option>
                  <option value="VT">Vermont</option>
                  <option value="VA">Virginia</option>
                  <option value="WA">Washington</option>
                  <option value="WV">West Virginia</option>
                  <option value="WI">Wisconsin</option>
                  <option value="WY">Wyoming</option>
                </select>
              </div>
            </div>
            <!-- Form Row 2 -->
            <div class="form-row">
              <div class="col-md-6 mb-3">
                <label class="sr-only">Bedrooms</label>
                <select name="bedrooms" class="form-control">
                  <option selected="true" disabled="disabled">Bedrooms (All)</option>
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                  <option value="5">5</option>
                  <option value="6">6</option>
                  <option value="7">7</option>
                  <option value="8">8</option>
                  <option value="9">9</option>
                  <option value="10">10</option>
                </select>
              </div>
              <div class="col-md-6 mb-3">
                <select name="price" class="form-control" id="type">
                  <option selected="true" disabled="disabled">Max Price (Any)</option>
                  <option value="100000">$100,000</option>
                  <option value="200000">$200,000</option>
                  <option value="300000">$300,000</option>
                  <option value="400000">$400,000</option>
                  <option value="500000">$500,000</option>
                  <option value="600000">$600,000</option>
                  <option value="700000">$700,000</option>
                  <option value="800000">$800,000</option>
                  <option value="900000">$900,000</option>
                  <option value="1000000">$1M+</option>
                </select>
              </div>
            </div>
            <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Listings -->
<section id="listings" class="py-5">
  <div class="container">
    <h3 class="text-center mb-3">Latest Listings</h3>
    <div class="row">
      <!-- Listing 1 -->
      <div class="col-md-6 col-lg-4 mb-4">
        <div class="card listing-preview">
          <img class="card-img-top" src="assets/img/homes/home-1.jpg" alt="">
          <div class="card-img-overlay">
            <h2>
              <span class="badge badge-secondary text-white">$490,000</span>
            </h2>
          </div>
          <div class="card-body">
            <div class="listing-heading text-center">
              <h4 class="text-primary">45 Drivewood Circle</h4>
              <p>
                <i class="fas fa-map-marker text-secondary"></i> Norwood MA, 02062</p>
            </div>
            <hr>
            <div class="row py-2 text-secondary">
              <div class="col-6">
                <i class="fas fa-th-large"></i> Sqft: 2500</div>
              <div class="col-6">
                <i class="fas fa-car"></i> Garage: 2</div>
            </div>
            <div class="row py-2 text-secondary">
              <div class="col-6">
                <i class="fas fa-bed"></i> Bedrooms: 3</div>
              <div class="col-6">
                <i class="fas fa-bath"></i> Bathrooms: 2</div>
            </div>
            <hr>
            <div class="row py-2 text-secondary">
              <div class="col-6">
                <i class="fas fa-user"></i> Kyle Brown</div>
            </div>
            <div class="row text-secondary pb-2">
              <div class="col-6">
                <i class="fas fa-clock"></i> 5 days ago</div>
            </div>
            <hr>
            <a href="listing.html" class="btn btn-primary btn-block">More Info</a>
          </div>
        </div>
      </div>

      <!-- Listing 2 -->
      <div class="col-md-6 col-lg-4 mb-4">
        <div class="card listing-preview">
          <img class="card-img-top" src="assets/img/homes/home-2.jpg" alt="">
          <div class="card-img-overlay">
            <h2>
              <span class="badge badge-secondary text-white">$550,000</span>
            </h2>
          </div>
          <div class="card-body">
            <div class="listing-heading text-center">
              <h4 class="text-primary">18 Jefferson Lane</h4>
              <p>
                <i class="fas fa-map-marker text-secondary"></i> Woburn MA, 01801</p>
            </div>
            <hr>
            <div class="row py-2 text-secondary">
              <div class="col-6">
                <i class="fas fa-th-large"></i> Sqft: 3200</div>
              <div class="col-6">
                <i class="fas fa-car"></i> Garage: 1</div>
            </div>
            <div class="row py-2 text-secondary">
              <div class="col-6">
                <i class="fas fa-bed"></i> Bedrooms: 4</div>
              <div class="col-6">
                <i class="fas fa-bath"></i> Bathrooms: 2.5</div>
            </div>
            <hr>
            <div class="row py-2 text-secondary">
              <div class="col-6">
                <i class="fas fa-user"></i> Mark Hudson</div>
            </div>
            <div class="row text-secondary pb-2">
              <div class="col-6">
                <i class="fas fa-clock"></i> 5 days ago</div>
            </div>
            <hr>
            <a href="listing.html" class="btn btn-primary btn-block">More Info</a>
          </div>
        </div>
      </div>

      <!-- Listing 3 -->
      <div class="col-md-6 col-lg-4 mb-4">
        <div class="card listing-preview">
          <img class="card-img-top" src="assets/img/homes/home-3.jpg" alt="">
          <div class="card-img-overlay">
            <h2>
              <span class="badge badge-secondary text-white">$580,000</span>
            </h2>
          </div>
          <div class="card-body">
            <div class="listing-heading text-center">
              <h4 class="text-primary">187 Woodrow Street</h4>
              <p>
                <i class="fas fa-map-marker text-secondary"></i> Salem MA, 01915</p>
            </div>
            <hr>
            <div class="row py-2 text-secondary">
              <div class="col-6">
                <i class="fas fa-th-large"></i> Sqft: 3107</div>
              <div class="col-6">
                <i class="fas fa-car"></i> Garage: 0</div>
            </div>
            <div class="row py-2 text-secondary">
              <div class="col-6">
                <i class="fas fa-bed"></i> Bedrooms: 4</div>
              <div class="col-6">
                <i class="fas fa-bath"></i> Bathrooms: 3</div>
            </div>
            <hr>
            <div class="row py-2 text-secondary">
              <div class="col-6">
                <i class="fas fa-user"></i> Mark Hudson</div>
            </div>
            <div class="row text-secondary pb-2">
              <div class="col-6">
                <i class="fas fa-clock"></i> 5 days ago</div>
            </div>
            <hr>
            <a href="listing.html" class="btn btn-primary btn-block">More Info</a>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>

<section id="services" class="py-5 bg-secondary text-white" style="background: url(/static/images/building.jpg);">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-4">
        <i class="fas fa-comment fa-4x mr-4"></i>
        <hr>
        <h3>Consulting Services</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, debitis nam! Repudiandae, provident iste consequatur
          hic dignissimos ratione ea quae.</p>
      </div>
      <div class="col-md-4">
        <i class="fas fa-home fa-4x mr-4"></i>
        <hr>
        <h3>Propery Management</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, debitis nam! Repudiandae, provident iste consequatur
          hic dignissimos ratione ea quae.</p>
      </div>
      <div class="col-md-4">
        <i class="fas fa-suitcase fa-4x mr-4"></i>
        <hr>
        <h3>Renting & Selling</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, debitis nam! Repudiandae, provident iste consequatur
          hic dignissimos ratione ea quae.</p>
      </div>
    </div>
  </div>
</section>
{% endblock %}

btrealestate/templates/navbar.html
{% load static %}

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">
      <img src="{% static "images/logo.png" %}" class="logo" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav">
        <li
          {% if '/' == request.path %}
            class="nav-item active mr-3"
          {% else %}
            class="nav-item mr-3"
          {% endif %}
        >
          <a class="nav-link" href="{% url 'home' %}">Home</a>
        </li>

        <li
          {% if 'about' in request.path %}
            class="nav-item active mr-3"
          {% else %}
            class="nav-item mr-3"
          {% endif %}
        >
          <a class="nav-link" href="{% url 'pages:about' %}">About</a>
        </li>

        <li
          {% if 'listings' in request.path %}
            class="nav-item active mr-3"
          {% else %}
            class="nav-item mr-3"
          {% endif %}
        >
          <a class="nav-link" href="{% url 'listings:listingsView' %}">Featured Listings</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item mr-3">
          <a class="nav-link" href="register.html">
            <i class="fas fa-user-plus"></i> Register</a>
        </li>
        <li class="nav-item mr-3">
          <a class="nav-link" href="login.html">
            <i class="fas fa-sign-in-alt"></i>

            Login</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

btrealestate/templates/topbar.html
{% load static %}

<!-- Top Bar -->
<section id="top-bar" class="p-3">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <i class="fas fa-phone"></i> (617)-555-5555
      </div>
      <div class="col-md-4">
        <i class="fas fa-envelope-open"></i> contact@btrealestate.co
      </div>
      <div class="col-md-4">
        <div class="social text-right">
          <a href="#">
            <i class="fab fa-twitter"></i>
          </a>
          <a href="#">
            <i class="fab fa-facebook"></i>
          </a>
          <a href="#">
            <i class="fab fa-linkedin"></i>
          </a>
          <a href="#">
            <i class="fab fa-instagram"></i>
          </a>
          <a href="#">
            <i class="fab fa-pinterest"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
</section>

listings/templates/listings/listing.html
{% extends "base.html" %}
{% load static %}

{% block title %}

{% endblock %}

{% block content %}
<section id="showcase-inner" class="py-5 text-white">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12">
        <h1 class="display-4">45 Drivewood Circle</h1>
        <p class="lead">
          <i class="fas fa-map-marker"></i> Norwood MA, 02062</p>
      </div>
    </div>
  </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
  <div class="container">
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="index.html">Home</a>
        </li>
        <li class="breadcrumb-item">
          <a href="listings.html">Listings</a>
        </li>
        <li class="breadcrumb-item active">42 Drivewood Circle</li>
      </ol>
    </nav>
  </div>
</section>

<!-- Listing -->
<section id="listing" class="py-4">
  <div class="container">
    <a href="listings.html" class="btn btn-light mb-4">Back To Listings</a>
    <div class="row">
      <div class="col-md-9">
        <!-- Home Main Image -->
        <img src="assets/img/homes/home-1.jpg" alt="" class="img-main img-fluid mb-3">
        <!-- Thumbnails -->
        <div class="row mb-5 thumbs">
          <div class="col-md-2">
            <a href="assets/img/homes/home-inside-1.jpg" data-lightbox="home-images">
              <img src="assets/img/homes/home-inside-1.jpg" alt="" class="img-fluid">
            </a>
          </div>
          <div class="col-md-2">
            <a href="assets/img/homes/home-inside-2.jpg" data-lightbox="home-images">
              <img src="assets/img/homes/home-inside-2.jpg" alt="" class="img-fluid">
            </a>
          </div>
          <div class="col-md-2">
            <a href="assets/img/homes/home-inside-3.jpg" data-lightbox="home-images">
              <img src="assets/img/homes/home-inside-3.jpg" alt="" class="img-fluid">
            </a>
          </div>
          <div class="col-md-2">
            <a href="assets/img/homes/home-inside-4.jpg" data-lightbox="home-images">
              <img src="assets/img/homes/home-inside-4.jpg" alt="" class="img-fluid">
            </a>
          </div>
          <div class="col-md-2">
            <a href="assets/img/homes/home-inside-5.jpg" data-lightbox="home-images">
              <img src="assets/img/homes/home-inside-5.jpg" alt="" class="img-fluid">
            </a>
          </div>
          <div class="col-md-2">
            <a href="assets/img/homes/home-inside-6.jpg" data-lightbox="home-images">
              <img src="assets/img/homes/home-inside-6.jpg" alt="" class="img-fluid">
            </a>
          </div>
        </div>
        <!-- Fields -->
        <div class="row mb-5 fields">
          <div class="col-md-6">
            <ul class="list-group list-group-flush">
              <li class="list-group-item text-secondary">
                <i class="fas fa-money-bill-alt"></i> Asking Price:
                <span class="float-right">$490,000</span>
              </li>
              <li class="list-group-item text-secondary">
                <i class="fas fa-bed"></i> Bedrooms:
                <span class="float-right">3</span>
              </li>
              <li class="list-group-item text-secondary">
                <i class="fas fa-bath"></i> Bathrooms:
                <span class="float-right">2</span>
              </li>
              <li class="list-group-item text-secondary">
                <i class="fas fa-car"></i> Garage:
                <span class="float-right">2
                </span>
              </li>
            </ul>
          </div>
          <div class="col-md-6">
            <ul class="list-group list-group-flush">
              <li class="list-group-item text-secondary">
                <i class="fas fa-th-large"></i> Square Feet:
                <span class="float-right">3200</span>
              </li>
              <li class="list-group-item text-secondary">
                <i class="fas fa-square"></i> Lot Size:
                <span class="float-right">2.5 Acres
                </span>
              </li>
              <li class="list-group-item text-secondary">
                <i class="fas fa-calendar"></i> Listing Date:
                <span class="float-right">8/30/2018</span>
              </li>
              <li class="list-group-item text-secondary">
                <i class="fas fa-bed"></i> Realtor:
                <span class="float-right">Kyle Brown
                </span>
              </li>


            </ul>
          </div>
        </div>

        <!-- Description -->
        <div class="row mb-5">
          <div class="col-md-12">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia recusandae esse reiciendis officia omnis non rerum dicta
            cupiditate nostrum molestias deserunt aut minus inventore animi atque, consequuntur ad fugit. Possimus culpa
            blanditiis repellendus ipsa similique ullam, natus error dolor harum.
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card mb-3">
          <img class="card-img-top" src="assets/img/realtors/kyle.jpg" alt="Seller of the month">
          <div class="card-body">
            <h5 class="card-title">Property Realtor</h5>
            <h6 class="text-secondary">Kyle Brown</h6>
          </div>
        </div>
        <button class="btn-primary btn-block btn-lg" data-toggle="modal" data-target="#inquiryModal">Make An Inquiry</button>
      </div>
    </div>
  </div>
</section>

<!-- Inquiry Modal -->
<div class="modal fade" id="inquiryModal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="inquiryModalLabel">Make An Inquiry</h5>
        <button type="button" class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="property_name" class="col-form-label">Property:</label>
            <input type="text" name="listing" class="form-control" value="45 Drivewood Cirlce" disabled>
          </div>
          <div class="form-group">
            <label for="name" class="col-form-label">Name:</label>
            <input type="text" name="name" class="form-control" required>
          </div>
          <div class="form-group">
            <label for="email" class="col-form-label">Email:</label>
            <input type="email" name="email" class="form-control" required>
          </div>
          <div class="form-group">
            <label for="phone" class="col-form-label">Phone:</label>
            <input type="text" name="phone" class="form-control">
          </div>
          <div class="form-group">
            <label for="message" class="col-form-label">Message:</label>
            <textarea name="message" class="form-control"></textarea>
          </div>
          <hr>
          <input type="submit" value="Send" class="btn btn-block btn-secondary">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

pages/templates/pages/about.html
{% extends "base.html" %}
{% load static %}

{% block title %}

{% endblock %}

{% block content %}
<section id="showcase-inner" class="py-5 text-white" style="background: url(/static/images/building.jpg);">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12">
        <h1 class="display-4">About BT Real Estate</h1>
        <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
      </div>
    </div>
  </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'home' %}">
            <i class="fas fa-home"></i> Home</a>
        </li>
        <li class="breadcrumb-item active"> About</li>
      </ol>
    </nav>
  </div>
</section>

<section id="about" class="py-4">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <h2>We Search For The Perfect Home</h2>
        <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
        <img src="assets/img/about.jpg" alt="">
        <p class="mt-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis esse officia repudiandae ad saepe ex, amet
          neque quod accusamus rem quia magnam magni dolorum facilis ullam minima perferendis? Exercitationem at quaerat
          commodi id libero eveniet harum perferendis laborum molestias quia.</p>
      </div>
      <div class="col-md-4">
        <div class="card">
          <img class="card-img-top" src="assets/img/realtors/kyle.jpg" alt="Seller of the month">
          <div class="card-body">
            <h5 class="card-title">Seller Of The Month</h5>
            <h6 class="text-secondary">Kyle Brown</h6>
            <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis nesciunt amet, illo itaque similique repellat.
              content.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Work -->
<section id="work" class="bg-dark text-white text-center">
  <h2 class="display-4">We Work For You</h2>
  <h4>Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem velit aperiam, unde aliquid at similique!</h4>
  <hr>
  <a href="listings.html" class="btn btn-secondary text-white btn-lg">View Our Featured Listings</a>
</section>

<!-- Team -->
<section id="team" class="py-5">
  <div class="container">
    <h2 class="text-center">Our Team</h2>
    <div class="row text-center">
      <div class="col-md-4">
        <img src="assets/img/realtors/kyle.jpg" alt="" class="rounded-circle mb-3">
        <h4>Kyle Brown</h4>
        <p class="text-success">
          <i class="fas fa-award text-success mb-3"></i> Realtor</p>
        <hr>
        <p>
          <i class="fas fa-phone"></i> (555)-555-5555</p>
        <p>
          <i class="fas fa-envelope-open"></i> kyle@btrealestate.co</p>
      </div>

      <div class="col-md-4">
        <img src="assets/img/realtors/mark.jpg" alt="" class="rounded-circle mb-3">
        <h4>Mark Hudson</h4>
        <p class="text-success">Realtor</p>
        <hr>
        <p>
          <i class="fas fa-phone"></i> (444)-444-4444</p>
        <p>
          <i class="fas fa-envelope-open"></i> mark@btrealestate.co</p>
      </div>

      <div class="col-md-4">
        <img src="assets/img/realtors/jenny.jpg" alt="" class="rounded-circle mb-3">
        <h4>Jenny Johnson</h4>
        <p class="text-success">Realtor</p>
        <hr>
        <p>
          <i class="fas fa-phone"></i> (333)-333-3333</p>
        <p>
          <i class="fas fa-envelope-open"></i> jenny@btrealestate.co</p>
      </div>
    </div>
  </div>
</section>
{% endblock %}